CREATE TABLE recycling.RecyclingAlerts (
    AlertID INT IDENTITY(1,1) PRIMARY KEY,
    BusinessID INT FOREIGN KEY REFERENCES recycling.Businesses(BusinessID),
    AlertType NVARCHAR(50), -- 'SCHEDULE_CHANGE', 'NEW_SERVICE', 'CONTAMINATION_FEEDBACK'
    Title NVARCHAR(200),
    Content NVARCHAR(MAX),
    Severity NVARCHAR(20),
    ValidFrom DATETIME2,
    ValidTo DATETIME2,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);